set nocompatible
set modeline
set encoding=utf-8 fileencodings=ucs-bom,utf-8,cp949,korea,iso-2022-kr
setlocal spelllang=en_us
set et
set nu
set smartindent autoindent
set ruler
set hlsearch
set incsearch
set ignorecase smartcase
set history=999
set undolevels=999

set autoread
set nobackup

set showmatch
set showmode
set laststatus=2
set title

set expandtab
set softtabstop=2
set tabstop=2
set smarttab
set copyindent


set ts=2 sts=2 sw=2
"set cursorline
set background=dark
set ttymouse=xterm2

set rtp+=~/.fzf
nmap <leader>f :FZF<CR>

set guioptions=egmrLt
set linespace=1
set backspace=2
set modeline
set encoding=utf-8 fileencodings=ucs-bom,utf-8,cp949,korea,iso-2022-kr

setlocal spelllang=en_us

syntax on
au FileType cpp        setl ts=2 sw=2 sts=2
"au FileType cpp        let g:ycm_global_ycm_extra_conf = '~/.vim/.ycm_extra_conf.py'
au FileType c          setl ts=2 sw=2 sts=2
"au FileType c          let g:ycm_global_ycm_extra_conf = '~/.vim/.ycm_extra_conf.py'
au FileType h          setl ts=2 sw=2 sts=2
au FileType py         setl ts=2 sw=2 sts=2
"au FileType py          let g:ycm_global_ycm_extra_conf = '~/.vim/.ycm_extra_conf.py'
au FileType md         setl ts=4 sw=4 sts=4
au FileType make       setl ts=4 sw=4 sts=4 noet

highlight ColorColumn cterm=underline ctermbg=none
autocmd BufWinEnter * match Error /\%>79v.\+\|\s\+$\|^\s*\n\+\%$/

function! InsertTabWrapper()
  let col=col('.')-1
  if !col||getline('.')[col-1]!~'\k'
    return "\<TAB>"
  else
    if pumvisible()
      return "\<C-N>"
    else
      return "\<C-N>\<C-P>"
    end
  endif
endfunction

inoremap <TAB> <c-r>=InsertTabWrapper()<cr>

"hi Pmenu ctermbg=blue
hi PmenuSel ctermbg=yellow ctermbg=black
"hi PmenuSbar ctermbg=blue

call plug#begin('~/.vim/plugged')
Plug 'scrooloose/nerdtree'
"Plug 'davidhalter/jedi-vim'
map <C-n> :NERDTreeToggle<CR>
Plug 'Valloric/YouCompleteMe'
let g:ycm_global_ycm_extra_conf = '~/.vim/.ycm_extra_conf.py'
let g:ycm_confirm_extra_conf = 0
Plug '~/.fzf'
call plug#end()
