# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Cuda
# export PATH="/usr/local/cuda/bin:$PATH"
# export LD_LIBRARY_PATH="/usr/local/cuda/lib64:$LD_LIBRARY_PATH"

# Path to your oh-my-zsh installation.
export ZSH="/home/jin/.oh-my-zsh"
ZSH_THEME="daveverwer"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias pre="cd .."
alias per="cd .."
alias home="cd ~"
alias root="cd /"
alias gits="git status"
alias gitc="git commit"
alias gita="git add"

alias gitd="git diff"
alias gitdc="git diff --cached"

alias gitst="git stash"
alias gitstl="git stash list"
alias gitstp="git stash pop"

alias gitl="git log"
alias gitlp="git log -p"
alias gitlg="git log --oneline --graph --decorate --abbrev-commit"

source /home/jin/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

NC='\033[0m'
Red='\033[0;31m'
Green='\033[0;32m'
Brown='\033[0;33m'
Blue='\033[0;34m'
Purple='\033[0;35m'
Cyan='\033[0;36m'
LightGray='\033[0;37m'
DarkGray='\033[1;30m'
LightRed='\033[1;31m'
LightGreen='\033[1;32m'
Yellow='\033[1;33m'
LightBlue='\033[1;34m'
LightPurple='\033[1;35m'
LightCyan='\033[1;36m'
White='\033[1;37m'

print_greeting () {
  hour=$1
  if [ $hour -ge 6 ] && [ $hour -lt 12 ]
  then
    echo -e "${Yellow} 진님 좋은 아침입니다!"
  elif [ $hour -ge 12 ] && [ $hour -lt 18 ]
  then
    echo -e "${Cyan} Good Afternoon, Jin ;)"
  elif [ $hour -ge 18 ] && [ $hour -lt 24 ]
  then
    echo -e "${Green} Good Evening~!"
  else
    echo -e "${LightGray} Good Night ZzZz.."
  fi
}

echo -e "${LightGreen}========================================================"
echo -e "   ${Brown}[$(whoami)]   [$(hostname)]   ${NC}`date`"
echo -e "${LightGreen}========================================================"
hour=`date +"%H"`
print_greeting $hour
echo -e "${LightGreen}========================================================"

export EDITOR=nvim

# Unity .Net path https://github.com/OmniSharp/omnisharp-vim/wiki/Unity3D-and-.NET-Framework
# export FrameworkPathOverride=/usr/lib/mono/4.7.1-api

